"""rename hashed_password to password

Revision ID: 5fbf715b070c
Revises: 40754033da40
Create Date: 2026-01-18 22:26:25.530070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fbf715b070c'
down_revision = '40754033da40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=True))
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
